### ISSUE TITLE
Color suggestions (aka nitpick-o-rama)

### ISSUE THREAD

**Issue by multicolorist** [felix-bohlin/cozy-dark#2]
Hi again, thanks a lot for the quick turnaround for fixing the theme! Updated and it works great.

I do have some suggestions, and mind you that these are just matters of taste and fine details on an already great theme.

## 1) Three points, a,b and c

I'd personally like when the border colors are less distinct/in your face, I'm referring to the RGB(51,63,74) in the following pictures, a) separating the activity bar and b) especially the underneath the editor tabs:

![Screenshot 2023-11-21 at 20 56 09](https://github.com/felix-bohlin/cozy-dark/assets/8113511/55184a4a-c62c-4463-996d-9dd9b8f265d1)
![Screenshot 2023-11-21 at 20 58 52](https://github.com/felix-bohlin/cozy-dark/assets/8113511/b6b8be39-2381-47ec-8b63-20fd50692ec6)

Compare this with a theme such as "Enki Aster Green", where the border are much less marked but still clear enough:
![Screenshot 2023-11-21 at 20 59 54](https://github.com/felix-bohlin/cozy-dark/assets/8113511/3e586d00-f0c4-41bf-825d-1fcc4cf6cfce)

Also, c) could be that the color of the icons and of the vertical "selection indication" of the the selected icon in the activity bar is almost pure white, which stands out from the rest of the theme, and I'd probably prefer it to be much more muted.

## 2) Just one point
I'd prefer the activity bar to be a darker color than an editor, since it's of less immediate relevance (it's often clear from main window context which mode one is in) while the colors suggest them to be of similar importance.

Weeeell that's my nitpicky wishes, do with them what you like!

**Comment by felix-bohlin** [comment]
Thanks for the input! I'll experiment a bit during the week and feel it out. The borders are a bit off, you're right. 

Regarding the activity bar I'm of the same opinion but amusingly enough I feel that by giving it the same color as everything else it "fades away" into the periphery. That's generally the idea of the whole theme as well tbh - tone down the visual hierarchy a little while having great syntax highlighting that works anywhere. I will of course try things out anyway to see if it's better.

**Comment by felix-bohlin** [comment]
Ok @multicolorist, in this new release I've done a lot of changes! Muted a lot of whites, I think I've addressed all of your points and lots more. Thanks for opening issues, don't be a stranger! :)

**Comment by multicolorist** [comment]
Really enjoying the changes, great work! 👍🏽🌻

I can see now what you mean with the sidebar fading away if it has the same color btw. I do like this though, so both options seem like good choices. Cheers!

**Comment by felix-bohlin** [comment]
Yeah I'm quite pleased now. There are of course some known issues left still, but all-in-all it feels good! Perhaps I should add the known issues here on github, it's not a bad idea... 😄
